### ISSUE TITLE
What does the expo compatibility flag mean?

### ISSUE THREAD

**Issue by maximilian-ruppert** [expo/react-native-libraries#12]
Hi, I'm fairly new to expo and react native and stumbled accross native.directory today. Sorry if this is maybe not the best place to ask this, but what does the expo compatibility flag mean? 
Does it mean I can use a component in my expo directly, or only if I detach it?
Would be great if I could link a non expo component to my expo app without detaching it.
Thanks for your help!

**Comment by jimmylee** [comment]
Hey @maximilian-ruppert I'm really glad you're here!

Expo compatibility means that you can use this Library in Expo without detaching.

If Expo is false, that means you have to detach to use it.

**Comment by maximilian-ruppert** [comment]
Hi @jimmylee, thanks for your quick reply.
Based on that answer I have a follow up question if you don't mind:
So if I would like to use one of the other components, like React Native Image Resizer, all I got to do is install it via npm right? 
And they only work in Expo not Create React Native App?
Thanks so much for your help and the work you and the Expo team do!
