### ISSUE TITLE
react-native-image-resizer seems to be incompatible with expo 

### ISSUE THREAD

**Issue by maximilian-ruppert** [expo/react-native-libraries#13]
Just tried using react-native-image-resizer in a simple expo project and I got an error. Seems like other people get this error as well. 

https://github.com/bamlab/react-native-image-resizer/issues/89

https://github.com/bamlab/react-native-image-resizer/issues/87

**Comment by jimmylee** [comment]
:+1: thanks for letting me know, I will update our data.
