### ISSUE TITLE
Feature: Form for adding libraries

### ISSUE THREAD

**Issue by krsjoseph** [expo/react-native-libraries#19]
Not really an issue but it would be great to have a form for adding libraries rather than updating the json file currently.

I know this would require a backend db and some sort of authentication so i'm thinking maybe using firebase or a mongo instance for the db and auth using github? 

Just some thoughts.

If approved, I'd love the opportunity to take it on and implement it.

**Comment by jimmylee** [comment]
The reasons why I like the PR process for adding a library:

- I can have a discussion with the person who is adding the library
- I can review and approve the library
- (subjective) It prevents someone from arbitrarily adding libraries and spamming our list, the list is supposed to be 'curated', we want to be careful with what we add.

I like the authentication idea, but I think its out of scope for now. I appreciate your interest though and I'll keep note of this as the project progresses.

**Comment by krsjoseph** [comment]
Thanks for the feedback. Understood
